### ISSUE TITLE
ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by SirCaelus** [pairofdocs/d2s_edit_recalc#1]
I keep getting this error when trying to reset quests like Forge or Izual

ValueError: invalid literal for int() with base 10: {name of quest}

I uncomment the line for the quest I want, i.e.:

# reset hellforge quest NM
495, 00 00

to

 reset hellforge quest NM
495, 00 00

Or even removing the space, but same error

**Comment by pairofdocs** [comment]
@SirCaelus
try 

```
# reset hellforge quest NM
495, 00 00
```

just those numbers need to be uncommented

and to disable it's
```
# reset hellforge quest NM
# 495, 00 00
```

**Comment by SirCaelus** [comment]
Ah I see, that did it. Quests successfully reset. Thanks a ton!!!
